version: '3.7'

services:

    sandbox:
        image: getsandboxlive
        container_name: sandbox
        volumes:
            - ./src:/base
            - ./state:/state
        ports: 
            - "8080:8080"
            - "8090:90"
        environment:
            - "WATCH=true"
            - "STATEFILE=default.json"
        

    sandbox_ngrok:
        image: wernight/ngrok
        container_name: sandbox_ngrok        
        depends_on:
            sandbox:
                condition: service_started
        links:
            - "sandbox"
        ports: 
            - "4040:4040"            
        command: ngrok http sandbox:8080
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:4040"]     

    jq_processor:
        image: dwdraju/alpine-curl-jq
        container_name: jq_processor        
        depends_on:
            sandbox_ngrok:
                condition: service_healthy
        links:
            - "sandbox_ngrok"         
        command: sh -c "curl -s http://sandbox_ngrok:4040/api/tunnels | jq '.tunnels[0].public_url'"